// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserService.proto

package name_nkonev_aaa

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserDto struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDto) Reset()         { *m = UserDto{} }
func (m *UserDto) String() string { return proto.CompactTextString(m) }
func (*UserDto) ProtoMessage()    {}
func (*UserDto) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{0}
}

func (m *UserDto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDto.Unmarshal(m, b)
}
func (m *UserDto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDto.Marshal(b, m, deterministic)
}
func (m *UserDto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDto.Merge(m, src)
}
func (m *UserDto) XXX_Size() int {
	return xxx_messageInfo_UserDto.Size(m)
}
func (m *UserDto) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDto.DiscardUnknown(m)
}

var xxx_messageInfo_UserDto proto.InternalMessageInfo

func (m *UserDto) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserDto) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *UserDto) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UsersRequest struct {
	UserIds              []int64  `protobuf:"varint,1,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{1}
}

func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (m *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(m, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

func (m *UsersRequest) GetUserIds() []int64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type UsersResponse struct {
	Users                []*UserDto `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7864342a5dd7108, []int{2}
}

func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (m *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(m, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetUsers() []*UserDto {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*UserDto)(nil), "name.nkonev.aaa.UserDto")
	proto.RegisterType((*UsersRequest)(nil), "name.nkonev.aaa.UsersRequest")
	proto.RegisterType((*UsersResponse)(nil), "name.nkonev.aaa.UsersResponse")
}

func init() { proto.RegisterFile("UserService.proto", fileDescriptor_e7864342a5dd7108) }

var fileDescriptor_e7864342a5dd7108 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xcb, 0xaa, 0xc2, 0x30,
	0x10, 0x40, 0x49, 0x42, 0x5b, 0xee, 0xdc, 0x17, 0x06, 0x91, 0x2c, 0x4b, 0x57, 0x59, 0x65, 0xa1,
	0x1f, 0x20, 0x88, 0x20, 0xee, 0x24, 0xe2, 0x07, 0x44, 0x3b, 0x48, 0x50, 0x93, 0x9a, 0xa4, 0xfd,
	0x7e, 0xe9, 0xc3, 0x8d, 0xcb, 0x33, 0x73, 0x18, 0xce, 0xc0, 0xec, 0x14, 0x31, 0x1c, 0x31, 0x74,
	0xf6, 0x82, 0xaa, 0x09, 0x3e, 0x79, 0xfe, 0xef, 0xcc, 0x03, 0x95, 0xbb, 0x79, 0x87, 0x9d, 0x32,
	0xc6, 0x54, 0x3b, 0x28, 0x7a, 0x6b, 0x9b, 0x3c, 0xff, 0x03, 0x6a, 0x6b, 0x41, 0x4a, 0x22, 0x99,
	0xa6, 0xb6, 0xe6, 0x73, 0xc8, 0xee, 0xfe, 0x6a, 0x9d, 0xa0, 0x25, 0x91, 0x5f, 0x7a, 0x04, 0xbe,
	0x80, 0xdc, 0x74, 0x26, 0x99, 0x20, 0xd8, 0x30, 0x9e, 0xa8, 0x92, 0xf0, 0xd3, 0x1f, 0x8a, 0x1a,
	0x9f, 0x2d, 0xc6, 0xc4, 0x05, 0x14, 0x6d, 0xc4, 0xb0, 0xaf, 0xa3, 0x20, 0x25, 0x93, 0x4c, 0xbf,
	0xb1, 0x5a, 0xc3, 0xef, 0x64, 0xc6, 0xc6, 0xbb, 0x88, 0x5c, 0x41, 0xd6, 0xef, 0x46, 0xf1, 0x7b,
	0x29, 0xd4, 0x47, 0xa4, 0x9a, 0x0a, 0xf5, 0xa8, 0x6d, 0xe8, 0x81, 0x9c, 0xf3, 0xe1, 0x9f, 0xd5,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x13, 0x72, 0x53, 0xe4, 0x00, 0x00, 0x00,
}
