// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LinkVideo struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewLinkVideo struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}
